spring:
  datasource:
    url: jdbc:postgresql://pgvector:5432/account_db
    username: account_user
    password: ${ACCOUNT_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET}

stripe:
  api:
    secret: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

app:
  frontend:
    url: ${APP_FRONTEND_URL}
