jwt:
  secretKey: ${JWT_SECRET}

app:
  security:
    publicRoutes:
      - /auth/signup
      - /auth/login
      - /webhooks/payment
      - /actuator/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service.lovable-core.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
          - prometheus
